openapi: "3.0.0"
info:
  version: 1.0.0
  title: API Versao
  license:
    name: MIT
servers:
  - url: http://localhost:19090/
paths:
  /versao:
    get:
      summary: Recuperar a versao da API
      operationId: recuperar a versao da API
      tags:
        - etcd
      responses:
        '200':
          description: um json com a versao da API